PAGINATED_MENUS:
  FILLER:
    NAME: '&7'
    MATERIAL: GRAY_STAINED_GLASS_PANE
    DATA: 0
    LORE: {}
  NEXT_PAGE:
    NAME: '&cNext Page'
    SOUND: UI_BUTTON_CLICK
    MATERIAL: GRAY_CARPET
    DATA: 0
    LORE: {}
  LAST_PAGE:
    NAME: '&cPrevious Page'
    SOUND: UI_BUTTON_CLICK
    MATERIAL: GRAY_CARPET
    DATA: 0
    LORE: {}

DISABLED_COMMANDS:
  MAIN_COMMANDS: []